### ISSUE TITLE
PeptideShaker

### ISSUE THREAD

**Issue by 02071974** [compomics/compomics.github.io#1]
(Harald Barsnes -  sofia.neves2009@gmail.com)
I need help I am trying for the first time to apply knowledge recently acquired in an IGC-Lisbon course. (That would be great for my PhD)

Back after two weeks in which I submitted a PeptideShaker - crashdown error report in which the algorithm used 32GB of RAM to look for probabilities associated with PTMs. I was helped and verified everything I was told at the time:
1-RAM available for the program, updated, 64-bit Java, sufficient
2- I performed experience with PSM search in only one search-machine, (X! Tandem)
3- And inhibited in the advanced configuration in the Searchgui and PeptideShaker of
location (click in "none").
(I have 52 raw data - orbitrap to search)
But this is the report I've been getting:
# ------------------------------------------------------------------
# PeptideShaker 1.16.39 Report File
#
# Originally saved by: Sofia @ STAR
#                  on: 11 May 2019, 21:31
#                  as: error Sofia Neves_ NO PTM localization _52 samples with PTM localization off_X!Tamdem_UpdatedPeptideShaker_Java8 211 64bits_ 4GB RAMmemory
# ------------------------------------------------------------------
Sat May 11 21:19:36 BST 2019        Import process for Tobacco Second Hand Exposure 11052019 (Sample: Human Nasal Epithelium, Replicate: 0)

Sat May 11 21:19:36 BST 2019        Importing sequences from 2018,_with_porcine_trypsine_concatenated_target_decoy.fasta.
Sat May 11 21:20:42 BST 2019        FASTA file import completed.
Sat May 11 21:20:42 BST 2019        Importing gene mappings.
Sat May 11 21:20:49 BST 2019        Establishing local database connection.
Sat May 11 21:21:03 BST 2019        Reading identification files.
Sat May 11 21:21:03 BST 2019        Parsing 131104_NB10_01.t.xml.
Sat May 11 21:21:06 BST 2019        Loading spectra for 131104_NB10_01.t.xml.
Sat May 11 21:21:06 BST 2019        Importing 131104_NB10_01.mgf
Sat May 11 21:21:07 BST 2019        131104_NB10_01.mgf imported.
Sat May 11 21:21:07 BST 2019        Importing PSMs from 131104_NB10_01.t.xml
Sat May 11 21:21:09 BST 2019        19 identified spectra (0.3%) did not present a valid peptide.
Sat May 11 21:21:09 BST 2019        304 of the best scoring peptides were excluded by the import filters:
Sat May 11 21:21:09 BST 2019            - 2.0% peptide mapping to both target and decoy.
Sat May 11 21:21:09 BST 2019            - 93.8% peptide length less than 8 or greater than 30.
Sat May 11 21:21:09 BST 2019            - 4.3% unrecognized modifications.
Sat May 11 21:21:09 BST 2019        Parsing 131104_NB11_01.t.xml.
Sat May 11 21:21:12 BST 2019        Loading spectra for 131104_NB11_01.t.xml.
Sat May 11 21:21:12 BST 2019        Importing 131104_NB11_01.mgf
Sat May 11 21:21:12 BST 2019        131104_NB11_01.mgf imported.
Sat May 11 21:21:12 BST 2019        Importing PSMs from 131104_NB11_01.t.xml
Sat May 11 21:21:14 BST 2019        PeptideShaker is encountering memory issues! See http://compomics.github.io/projects/peptide-shaker.html for help.
Sat May 11 21:21:14 BST 2019        Reducing Memory Consumption.
Sat May 11 21:21:29 BST 2019        17 identified spectra (0.3%) did not present a valid peptide.
Sat May 11 21:21:29 BST 2019        305 of the best scoring peptides were excluded by the import filters:
Sat May 11 21:21:29 BST 2019            - 1.6% peptide mapping to both target and decoy.
Sat May 11 21:21:29 BST 2019            - 94.4% peptide length less than 8 or greater than 30.
Sat May 11 21:21:29 BST 2019            - 3.9% unrecognized modifications.
Sat May 11 21:21:29 BST 2019        Parsing 131104_NB12_01.t.xml.
Sat May 11 21:21:32 BST 2019        Loading spectra for 131104_NB12_01.t.xml.
Sat May 11 21:21:32 BST 2019        Importing 131104_NB12_01.mgf
Sat May 11 21:21:32 BST 2019        131104_NB12_01.mgf imported.
Sat May 11 21:21:32 BST 2019        Importing PSMs from 131104_NB12_01.t.xml
Sat May 11 21:21:32 BST 2019        An error occurred: null
Sat May 11 21:21:32 BST 2019        Please contact the developers (https://github.com/compomics/peptide-shaker/issues).

Sat May 11 21:21:32 BST 2019        Importing Data Canceled!
The first error is in attachment

[PeptideShkaker 1.16.38_Error 2_Sofia Neves.txt](https://github.com/compomics/compomics.github.io/files/3169478/PeptideShkaker.1.16.38_Error.2_Sofia.Neves.txt)

**Comment by RalfG** [comment]
Hi,
This is the repository of our documentation website. If you still experience this issue, you can post it on the PeptideShaker issue tracker at [github.com/compomics/peptide-shaker/issues](https://github.com/compomics/peptide-shaker/issues).
Thanks!
